version: 2

sources:
  - name: linux_pl
    database: postgres  
    schema: target_public
    freshness: # default freshness
      # warn_after: {count: 12, period: hour}
      error_after: {count: 6, period: hour}
    loaded_at_field: _airbyte_emitted_at


    tables:
      - name: customer
        description: >
          Customer source description
        columns:
          - name: customer_id
            tests:
              - unique
              - not_null
      - name: rental
