version: 2

models:
  - name: customers
    description: | 
      ### Model description

      * One record per customer
      * Rental details for each customer

    columns:
      - name: customer_id
        description: Primary key
        tests:
          - unique
          - not_null

  - name: stg_customers
    description: This model cleans up customer data
    columns:
      - name: customer_id
        description: Primary key
        tests:
          - unique
          - not_null

  - name: stg_rentals
    description: This model cleans up rentals data
    columns:
      - name: rental_id
        description: Primary key
        tests:
          - unique
          - not_null
      # - name: status
      #   tests:
      #     - accepted_values:
      #         values: ['placed', 'shipped', 'completed', 'return_pending', 'returned']
      - name: customer_id
        description: Foreign key
        tests:
          - not_null
          - relationships:
              to: ref('stg_customers')
              field: customer_id